client_id = "5db55cf89a2c12312b4bb6e469a5cb93"
name = "AI Recommendations - By Boko"
application_url = "https://boko-reco-public.replit.app"
embedded = true

[access_scopes]
scopes = "read_products,read_orders,write_script_tags"

[auth]
redirect_urls = [ "https://boko-reco-public.replit.app/auth/callback" ]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://boko-reco-public.replit.app/webhooks/app_uninstalled"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "https://boko-reco-public.replit.app/webhooks/compliance"

[app_proxy]
url = "https://boko-reco-public.replit.app/proxy"
subpath = "reco"
prefix = "apps"

[pos]
embedded = false
