# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f960a64d8f1e317dc3df58fdfe8cef4d"
name = "Boko AI Recommendations 2"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_discounts,write_script_tags"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
